I stand corrected - it is possible to unit test this
Just a good illustration of why the cache invalidation problem is hard, and the way we’re using Ampersand has caches galore.

  110 passing (6s)
  5 pending
  2 failing

  1) ssh_tunnel IDENTITY_FILE triggers EISDIR error when calculating a derived property:
     AssertionError: Missing expected exception..
      at _throws (assert.js:339:5)
      at Function.assert.throws (assert.js:363:3)
      at Context.<anonymous> (test/ssh-tunnel.test.js:178:14)

  2) ssh_tunnel IDENTITY_FILE When `ssh_tunnel_passphrase` is provided ssh_tunnel_options driver_url does not change after setting multiple options:

      AssertionError: 'mongodb://127.0.0.1:29424/?slaveOk=true' == 'mongodb://127.0.0.1:29864/?slaveOk=true'
      + expected - actual

      -mongodb://127.0.0.1:29424/?slaveOk=true
      +mongodb://127.0.0.1:29864/?slaveOk=true

      at Context.<anonymous> (test/ssh-tunnel.test.js:282:18)