COMPASS-503 SSH + Auth (#142)
* COMPASS 503: SSH Tunnel + Auth

Update tests to detect the SSH tunnel issue

Ampersand models are complicated.

* Turns out this scenario doesn’t seem unit-testable

The actual chain was something like (paraphrasing as there are many implementation details):
1. In Compass (private repo), on successful test connection, we save any passwords to secure storage, e.g. macOS keychain.
2. This causes an Ampersand update of derived properties (across two intricately coupled models, go figure - want to rewrite with Redux stores).
3. In the case of SSH Tunnel + Auth, we have the derived properties of both the SCRAM-SHA-1 password and the SSH Tunnel passphrase.
4. So we get two triggered Ampersand model update events for the derived Ampersand property, causing the next model.driver_url to be different to the next SSH Tunnel that is to be created.
5. Hence we shouldn’t be using a derived Ampersand property, which is the incoming fix, but not AFAICT unit-testable as it’s too many chained callbacks and there’s no obvious smoking gun for “that’s clearly wrong”, just the side-effects this many layers down.

* I stand corrected - it is possible to unit test this

Just a good illustration of why the cache invalidation problem is hard, and the way we’re using Ampersand has caches galore.

  110 passing (6s)
  5 pending
  2 failing

  1) ssh_tunnel IDENTITY_FILE triggers EISDIR error when calculating a derived property:
     AssertionError: Missing expected exception..
      at _throws (assert.js:339:5)
      at Function.assert.throws (assert.js:363:3)
      at Context.<anonymous> (test/ssh-tunnel.test.js:178:14)

  2) ssh_tunnel IDENTITY_FILE When `ssh_tunnel_passphrase` is provided ssh_tunnel_options driver_url does not change after setting multiple options:

      AssertionError: 'mongodb://127.0.0.1:29424/?slaveOk=true' == 'mongodb://127.0.0.1:29864/?slaveOk=true'
      + expected - actual

      -mongodb://127.0.0.1:29424/?slaveOk=true
      +mongodb://127.0.0.1:29864/?slaveOk=true

      at Context.<anonymous> (test/ssh-tunnel.test.js:282:18)

* Add ssh_tunnel_bind_to_local_port prop and initialize() it

So it’s not a derived property (really don’t want to learn too much about Ampersand if we’re moving to Reflux or Redux stores).
Fixes the ampersand store’s derived state changing when called multiple times, like when we connect to a remote instance.

* See COMPASS-460: Temporarily skip 2.6 TravisCI Tests

* Skip all the 2.6 Cluster tests

* Hopefully actually skip 2.6 tests